# addReviewers: true
# addAssignees: false
# numberOfReviewers: 1

# reviewers:
#   - data-platform-lead
#   - senior-data-engineer
#   - platform-architect

# assignees: []

# skipKeywords:
#   - wip
#   - draft

# filterLabels:
#   include:
#     - ready-for-review
#   exclude:
#     - work-in-progress

addReviewers: true
addAssignees: false
numberOfReviewers: 1

reviewers:
  - nandam-hub

assignees: []

skipKeywords:
  - wip
  - draft

filterLabels:
  include:
    - ready-for-review
  exclude:
    - work-in-progress

