# Dev Environment Configuration
environment:
  name: dev
  lh_environment: dev
  aws_environment: dev

databricks:
  host: ${SECRET:databricks-dev-credentials:host}
  client_id: ${SECRET:databricks-dev-credentials:client_id}
  client_secret: ${SECRET:databricks-dev-credentials:client_secret}
  auth_type: oauth-m2m

service_principal:
  id: ${SECRET:databricks-dev-credentials:service_principal_id}

permissions:
  - level: CAN_MANAGE
    group_name: LakehouseEnterpriseWorkspaceAdmin
  - level: CAN_MANAGE
    group_name: LakehouseSandboxDataEngineer
  - level: CAN_MANAGE
    user_name: ${workspace.current_user.userName}
  - level: CAN_MANAGE
    group_name: LakehouseEnterpriseWorkspaceDataEngineer
  - level: CAN_VIEW
    group_name: users

# Sub-environments for dev
sub_environments:
  - deva
  - devb
